name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - run: go build
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - run: echo "::add-path::~/go/bin"
      - name: Get release dependencies
        run: |
          go get github.com/mitchellh/gox
          go get github.com/tcnksm/ghr
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ghr: true
      - run: |
          gox -parallel 2 -osarch="linux/amd64 darwin/amd64 linux/arm linux/arm64 windows/amd64" -ldflags="-extldflags '-static' -s -w" -output="bin/{{.Dir}}_v${{steps.semrel.outputs.version}}_{{.OS}}_{{.Arch}}" .
          rename.ul amd64 x86_64 bin/*amd64
        if: steps.semrel.outputs.version != ''
      - run: ghr $(cat .ghr) bin/
        if: steps.semrel.outputs.version != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
